"""Generates tools/unicode_tables.py from the Unicode Character Database.

WIST-1 §2 and WIST-4 §5 read every Unicode property from one pinned
release (ADR-0017). This script fetches that release's property files and
writes the ranges `segmentation.py` needs, so the vector generator and the
validation harness stay offline and deterministic: the generated module is
committed, and this script is run only when the pinned version moves.

Usage: tools/.venv/bin/python tools/gen_unicode_tables.py
"""
import sys
import urllib.request
from pathlib import Path

VERSION = "16.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
OUT = Path(__file__).parent / "unicode_tables.py"

SOURCES = {
    "word_break": ("auxiliary/WordBreakProperty.txt", None),
    "grapheme_break": ("auxiliary/GraphemeBreakProperty.txt", None),
    "extended_pictographic": ("emoji/emoji-data.txt", {"Extended_Pictographic"}),
    "incb": ("DerivedCoreProperties.txt", {"InCB"}),
}


def fetch(path):
    with urllib.request.urlopen(BASE + path) as response:
        return response.read().decode("utf-8")


def parse(text, wanted):
    """Yields (first, last, value) from a UCD property file. `InCB` lines
    carry the value in a third field."""
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        rng, prop = fields[0], fields[1]
        if wanted is not None and prop not in wanted:
            continue
        if prop == "InCB":
            prop = fields[2]
        if ".." in rng:
            first, last = (int(x, 16) for x in rng.split(".."))
        else:
            first = last = int(rng, 16)
        yield first, last, prop


def ranges(entries):
    """Sorted, merged (first, last, value) with adjacent equal values joined."""
    out = []
    for first, last, value in sorted(entries):
        if out and out[-1][2] == value and out[-1][1] + 1 == first:
            out[-1] = (out[-1][0], last, value)
        else:
            out.append((first, last, value))
    return out


def emit(handle, name, entries):
    values = sorted({value for _, _, value in entries})
    index = {value: i for i, value in enumerate(values)}
    handle.write(f"\n{name}_VALUES = (\n")
    for value in values:
        handle.write(f"    {value!r},\n")
    handle.write(")\n")
    handle.write(f"\n{name} = (\n")
    for first, last, value in entries:
        handle.write(f"    (0x{first:X}, 0x{last:X}, {index[value]}),\n")
    handle.write(")\n")


def main():
    tables = {}
    for name, (path, wanted) in SOURCES.items():
        print(f"fetching {path}", file=sys.stderr)
        tables[name] = ranges(parse(fetch(path), wanted))
    with OUT.open("w", encoding="utf-8") as handle:
        handle.write('"""Generated by tools/gen_unicode_tables.py. Do not edit.\n\n')
        handle.write("Unicode property ranges for the release ADR-0017 pins.\n")
        handle.write('"""\n\n')
        handle.write(f"UNICODE_VERSION = {VERSION!r}\n")
        for name in ("word_break", "grapheme_break", "extended_pictographic", "incb"):
            emit(handle, name.upper(), tables[name])
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
